# Generated by Django 3.0 on 2019-12-19 17:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        ('bid', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SellItemIncrement',
            fields=[
                ('sellitem_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='bid.SellItem')),
                ('instant_sell', models.FloatField()),
                ('min_delta', models.FloatField(default=0)),
            ],
            bases=('bid.sellitem',),
        ),
        migrations.AddField(
            model_name='sellitem',
            name='current_price',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='sellitem',
            name='highest_payer',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.UserProfile'),
        ),
        migrations.AddField(
            model_name='sellitem',
            name='state',
            field=models.CharField(default='inactive', max_length=15),
        ),
        migrations.AlterField(
            model_name='item',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.UserProfile'),
        ),
        migrations.AlterField(
            model_name='sellitem',
            name='starting',
            field=models.FloatField(default=0),
        ),
    ]
