# Generated by Django 3.0 on 2019-12-19 21:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bid', '0002_auto_20191219_2015'),
    ]

    operations = [
        migrations.CreateModel(
            name='SellItemDecrement',
            fields=[
                ('sellitem_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='bid.SellItem')),
                ('period', models.FloatField()),
                ('delta', models.FloatField(default=0)),
                ('stop_decrement', models.FloatField(default=0)),
                ('last_bid', models.FloatField(default=0)),
            ],
            bases=('bid.sellitem',),
        ),
    ]
