# Generated by Django 3.0.1 on 2020-01-01 16:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bid', '0007_biddeduser_selliteminstantincrement'),
        ('bid', '0007_messages'),
    ]

    operations = [
    ]
