# Generated by Django 3.0.1 on 2020-01-08 17:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bid', '0008_merge_20200101_1610'),
    ]

    operations = [
        migrations.AddField(
            model_name='biddeduser',
            name='sell',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='bid.SellItem'),
        ),
    ]
