# Generated by Django 3.0.2 on 2020-01-12 12:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_remove_userprofile_email'),
        ('bid', '0010_auto_20200112_1229'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sellitem',
            name='sell_owner',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sell_owner', to='users.UserProfile'),
        ),
    ]
