# Generated by Django 3.0 on 2019-12-20 21:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        ('bid', '0003_sellitemdecrement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sellitemdecrement',
            name='delta',
            field=models.FloatField(),
        ),
        migrations.CreateModel(
            name='WatchSell',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sell', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bid.SellItem')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.UserProfile')),
            ],
        ),
        migrations.CreateModel(
            name='WatchItemTypes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_type', models.CharField(max_length=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.UserProfile')),
            ],
        ),
    ]
