# Generated by Django 3.0 on 2019-12-21 17:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bid', '0005_auto_20191221_0109'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sellitem',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bid.Item'),
        ),
    ]
