# Generated by Django 3.0 on 2019-12-21 18:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        ('bid', '0006_auto_20191221_2059'),
    ]

    operations = [
        migrations.CreateModel(
            name='SellItemInstantIncrement',
            fields=[
                ('sellitem_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='bid.SellItem')),
                ('total_bid', models.FloatField(default=0)),
                ('minbid', models.FloatField(default=0)),
                ('last_bid', models.FloatField(default=0)),
            ],
            bases=('bid.sellitem',),
        ),
        migrations.CreateModel(
            name='BiddedUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bid', models.FloatField(default=0)),
                ('bidded_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.UserProfile')),
            ],
        ),
    ]
