# Generated by Django 3.0 on 2019-12-22 16:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bid', '0008_watchitem'),
    ]

    operations = [
        migrations.DeleteModel(
            name='WatchItem',
        ),
    ]
