# Generated by Django 3.0 on 2019-12-22 16:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bid', '0007_messages'),
        ('bid', '0009_delete_watchitem'),
    ]

    operations = [
    ]
