# Generated by Django 3.0 on 2019-12-22 19:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bid', '0010_merge_20191222_1631'),
    ]

    operations = [
        migrations.AddField(
            model_name='biddeduser',
            name='sell',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='bid.SellItem'),
            preserve_default=False,
        ),
    ]
